"""HSM integration layer.

Production deployments should configure the Entrust Shield HSM endpoint
through environment variables. When no HSM is reachable (e.g. local dev)
the fallback uses a strongly-encrypted in-memory key generated by the
``cryptography`` library so the rest of the system can be exercised end
to end without leaking any plaintext key material.
"""

import os
import secrets
from typing import Optional

import requests
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.serialization import BestAvailableEncryption

from .config import HSM_API_KEY, HSM_ENDPOINT, HSM_VENDOR


class HSMIntegrationError(Exception):
    pass


class EntrustShieldHSMClient:
    """Thin REST client matching a generic Entrust Shield HSM API.

    Adapt the path templates here to match your appliance's REST schema or
    swap to the vendor-supplied PKCS#11 / KMIP SDK in a subclass.
    """

    def __init__(self, endpoint: str = HSM_ENDPOINT, api_key: str = HSM_API_KEY, vendor: str = HSM_VENDOR):
        self.endpoint = endpoint.rstrip('/')
        self.api_key = api_key
        self.vendor = vendor
        if not self.api_key:
            raise HSMIntegrationError('HSM_API_KEY environment variable is not configured.')

    def _headers(self) -> dict:
        return {
            'Authorization': f'Bearer {self.api_key}',
            'Content-Type': 'application/json',
            'X-HSM-Vendor': self.vendor,
        }

    def health(self) -> dict:
        try:
            r = requests.get(f'{self.endpoint}/health', headers=self._headers(), timeout=5)
            r.raise_for_status()
            return r.json()
        except requests.RequestException as exc:
            raise HSMIntegrationError(f'HSM health probe failed: {exc}') from exc

    def generate_key_pair(self, label: str, key_size: int = 3072, algorithm: str = 'RSA') -> dict:
        payload = {'label': label, 'algorithm': algorithm, 'key_size': key_size, 'purpose': 'signing'}
        r = requests.post(f'{self.endpoint}/keys', json=payload, headers=self._headers(), timeout=15)
        if r.status_code != 201:
            raise HSMIntegrationError(f'Failed to generate key pair: {r.status_code} {r.text}')
        return r.json()

    def sign_csr(self, csr_pem: str, key_id: str) -> x509.Certificate:
        payload = {'csr': csr_pem, 'key_id': key_id}
        r = requests.post(f'{self.endpoint}/sign', json=payload, headers=self._headers(), timeout=15)
        if r.status_code != 200:
            raise HSMIntegrationError(f'Failed to sign CSR: {r.status_code} {r.text}')
        cert_pem = r.json().get('certificate')
        return x509.load_pem_x509_certificate(cert_pem.encode())

    def generate_root_ca(self, common_name: str, key_size: int = 4096) -> dict:
        return self.generate_key_pair(label=f'root-ca-{common_name}', key_size=key_size)


class LocalHSMFallback:
    """Development fallback when no Entrust HSM is reachable.

    Key material never leaves memory unencrypted; the returned PEM is wrapped
    with a freshly generated symmetric passphrase that is *not* persisted.
    """

    def __init__(self):
        self.vendor = 'LocalHSMFallback'
        self._counter = 0

    def health(self) -> dict:
        return {'vendor': self.vendor, 'status': 'simulated', 'fips_140_3': 'not-applicable'}

    def generate_key_pair(self, label: str, key_size: int = 3072, algorithm: str = 'RSA') -> dict:
        self._counter += 1
        key = rsa.generate_private_key(public_exponent=65537, key_size=key_size)
        passphrase = secrets.token_urlsafe(24).encode()
        pem = key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=BestAvailableEncryption(passphrase),
        )
        pub = key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        return {
            'label': label,
            'algorithm': algorithm,
            'key_size': key_size,
            'key_id': f'local-{self._counter:04d}',
            'public_key_pem': pub.decode(),
            'private_key_pem': pem.decode(),
            'wrapped': True,
        }

    def sign_csr(self, csr_pem: str, key_id: str):
        raise HSMIntegrationError('Local fallback does not perform CSR signing; deploy a real HSM.')


def get_hsm_client():
    """Return the configured HSM client, falling back to the local stub."""
    if os.getenv('HSM_API_KEY'):
        try:
            return EntrustShieldHSMClient()
        except HSMIntegrationError:
            pass
    return LocalHSMFallback()
